"TAB BUTONLARI TANIMLADIĞIMIZ YER
SELECTION-SCREEN BEGIN OF TABBED BLOCK tb1 FOR 15 LINES.
  SELECTION-SCREEN TAB (10) t1 USER-COMMAND one.
  SELECTION-SCREEN TAB (10) t2 USER-COMMAND two.
SELECTION-SCREEN END OF BLOCK tb1.


"SUBSCREEN TANIMLANAN YER
SELECTION-SCREEN BEGIN OF SCREEN 1001 AS SUBSCREEN.
  PARAMETERS : p_d1 TYPE string,
               p_d2 TYPE string,
               p_d3 TYPE string.

  SELECTION-SCREEN SKIP 3.
  PARAMETERS p_d4 TYPE string.


  DATA lv_v1 TYPE string.

  SELECTION-SCREEN SKIP 2.
  SELECTION-SCREEN PUSHBUTTON 6(10) pb1 USER-COMMAND full.
  SELECTION-SCREEN PUSHBUTTON 30(10) pb2 USER-COMMAND clear.
  SELECTION-SCREEN PUSHBUTTON 54(10) pb3 USER-COMMAND exit.
SELECTION-SCREEN END OF SCREEN 1001.

"SUBSCREEN TANIMLANAN YER
SELECTION-SCREEN BEGIN OF SCREEN 1002 AS SUBSCREEN.

  "FRAME TANIMLANAN YER
  SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE tt1.               "TEXT-006.
    PARAMETERS : pp_d1 TYPE i DEFAULT 100 OBLIGATORY,
                 pp_d2 TYPE i DEFAULT 20 OBLIGATORY.
*             P_CB1 AS CHECKBOX,
*             P_CB2 AS CHECKBOX,
*             P_CB3 AS CHECKBOX,
*             P_CB4 AS CHECKBOX DEFAULT 'X'.
  SELECTION-SCREEN END OF BLOCK b2.

  SELECTION-SCREEN SKIP 2.

  "FRAME TANIMLANAN YER
  SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE tt2.                                      "TEXT-005.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 05.
      PARAMETERS p_cb1 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 07(08) TEXT-001.
      SELECTION-SCREEN POSITION 20.
      PARAMETERS p_cb2 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 22(08) TEXT-002.
      SELECTION-SCREEN POSITION 35.
      PARAMETERS p_cb3 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 37(08) TEXT-003.
      SELECTION-SCREEN POSITION 50.
      PARAMETERS p_cb4 AS CHECKBOX DEFAULT 'X'..
      SELECTION-SCREEN COMMENT 52(08) TEXT-004.

    SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN END OF SCREEN 1002.


INITIALIZATION.
  "DEFAULT TAB AYARLANAN YER
  tb1-activetab = 'TWO'.
  tb1-dynnr  = 1002.
  tb1-prog   = sy-repid. "PROGRAMIN ADINI TUTAN DEĞİŞKEN
  t1 = 'HELLO'.
  t2 = 'BYE'.
  pb1 = 'FULL NAME'.
  pb2 = 'CLEAR'.
  pb3 = 'EXIT'.
  tt1 = 'ENTER VALUE IN INPUT FIELDS'.
  tt2 = 'CHOOSE THE CHECK FOR APPROPERIATE ACTION'.

"LOJIK
START-OF-SELECTION.
  IF p_cb1 ='X'.
    lv_v1 = pp_d1 + pp_d2.
    WRITE :/ ' SUM RESULT IS --> ', lv_v1.
  ENDIF.

  IF p_cb2 ='X'.
    lv_v1 = pp_d1 - pp_d2.
    WRITE :/ ' SUBTRACTION RESULT IS --> ', lv_v1.
  ENDIF.

  IF p_cb3 ='X'.
    lv_v1 = pp_d1 * pp_d2.
    WRITE :/ ' PRODUCT RESULT IS --> ', lv_v1.
  ENDIF.

  IF p_cb4 ='X'.
    lv_v1 = pp_d1 / pp_d2.
    WRITE :/ ' DIVISION RESULT IS --> ', lv_v1.
  ENDIF.

"KULLANICININ SEÇİM YAPTIĞI DURUMDA ÇALIŞACAK LOJİK
AT SELECTION-SCREEN.
  CASE sy-dynnr. "SELECTION SCREEN NUMBER
    WHEN 1000.
      CASE sy-ucomm."FUNCTUON CODE BUTON
        WHEN 'ONE'.
          tb1-dynnr = 1001.
        WHEN 'FULL'.
*      CONCATENATE P_D1 P_D2 P_D3 INTO LV_V1 SEPARATED BY SPACE.
          CONCATENATE p_d1 p_d2 p_d3 INTO p_d4 SEPARATED BY space.
*      WRITE :/ 'FULL NAME IS :- ', LV_V1.
        WHEN 'CLEAR'.
          CLEAR : p_d1, p_d2, p_d3, p_d4.
        WHEN 'EXIT'.
          LEAVE PROGRAM.
        WHEN 'TWO'.
          tb1-dynnr = 1002.
      ENDCASE.
  ENDCASE.
