SELECTION-SCREEN BEGIN OF SCREEN 1001 AS SUBSCREEN NESTING LEVEL 1.

  SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE frame4.
    SELECTION-SCREEN BEGIN OF LINE.

      SELECTION-SCREEN POSITION 05.
      PARAMETERS p_rb1 RADIOBUTTON GROUP gp1 USER-COMMAND fc1.
      SELECTION-SCREEN COMMENT 07(15) TEXT-001.

      SELECTION-SCREEN POSITION 50.
      PARAMETERS p_rb2 RADIOBUTTON GROUP gp1 DEFAULT 'X'.
      SELECTION-SCREEN COMMENT 52(15) TEXT-002.

    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN SKIP 2.

    SELECTION-SCREEN BEGIN OF LINE.

      SELECTION-SCREEN COMMENT 06(18) TEXT-003 MODIF ID a1.
      SELECTION-SCREEN POSITION 25.
      PARAMETERS p_d1 TYPE vbak-kunnr MODIF ID a1.


      SELECTION-SCREEN COMMENT 51(20) TEXT-004 MODIF ID b1.
      SELECTION-SCREEN POSITION 72.
      PARAMETERS p_d2 TYPE vbak-vbeln MODIF ID b1.
      PARAMETERS p_d3 TYPE vbak-vbeln MODIF ID b1.

    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN SKIP 2.

    SELECTION-SCREEN PUSHBUTTON 6(25) pushbut3 USER-COMMAND ittoalv.
    SELECTION-SCREEN PUSHBUTTON 34(23) pushbut4 USER-COMMAND exit.

  SELECTION-SCREEN END OF BLOCK b4.

SELECTION-SCREEN END OF SCREEN 1001.
